import React, { useState } from 'react';
import { useSession } from '../context/SessionContext';
import MediatorChat from './MediatorChat';
import { MessageSquare, Target, CheckCircle2, ChevronRight } from 'lucide-react';

const Phase2COs = () => {
  const { sessionData } = useSession();
  const [chatOpen, setChatOpen] = useState(false);

  if (!sessionData) return <div className="page-wrapper" style={{ color: 'var(--text-secondary)' }}>Retrieving active session metrics...</div>;

  const cos = sessionData.cos || [];

  return (
    <div className="page-wrapper animate-fade-in" style={{ display: 'flex', gap: '2.5rem', alignItems: 'flex-start' }}>
      
      {/* Course Outcomes Panel */}
      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', gap: '1.75rem' }}>
        
        {/* Panel Header */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div>
            <h2 style={{ fontSize: '1.6rem', marginBottom: '0.25rem' }}>Course Outcomes (CO)</h2>
            <p style={{ color: 'var(--text-secondary)', margin: 0, fontSize: '0.85rem' }}>
              Review the curriculum outcomes generated by the Bloom Taxonomy Agent.
            </p>
          </div>
          
          <button 
            className="btn-secondary" 
            onClick={() => setChatOpen(!chatOpen)}
            style={{ 
              display: 'flex', 
              alignItems: 'center', 
              gap: '0.6rem',
              background: chatOpen ? 'var(--aurora-purple)' : '',
              color: chatOpen ? 'var(--text-dark)' : '',
              transform: chatOpen ? 'translate(2px, 2px)' : '',
              boxShadow: chatOpen ? '1px 1px 0px #000000' : ''
            }}
          >
            <MessageSquare size={16} color={chatOpen ? "var(--text-dark)" : "var(--text-secondary)"} />
            <span>AI Mediator Chat</span>
          </button>
        </div>

        {/* CO Cards Container */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
          {cos.map((co, index) => (
            <div key={co.co_id} className="bento-card" style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
              
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                  <div style={{
                    width: '32px',
                    height: '32px',
                    borderRadius: '4px',
                    background: 'var(--aurora-purple)',
                    border: '2px solid var(--border-thick)',
                    display: 'grid',
                    placeItems: 'center',
                    boxShadow: '2px 2px 0px #000000'
                  }}>
                    <Target size={16} color="var(--text-dark)" />
                  </div>
                  <h3 style={{ fontSize: '1.1rem', fontFamily: "'Space Grotesk', sans-serif", fontWeight: '700' }}>
                    {co.co_id}
                  </h3>
                </div>
                
                <span className="badge-bloom">
                  L{co.blooms_level} &bull; {co.blooms_keyword.toUpperCase()}
                </span>
              </div>
              
              <div style={{ display: 'flex', gap: '1rem', alignItems: 'flex-start' }}>
                <ChevronRight size={18} color="var(--aurora-purple)" style={{ marginTop: '0.2rem', flexShrink: 0 }} />
                <p style={{ margin: 0, fontSize: '1.05rem', lineHeight: '1.6', fontWeight: '500', color: 'var(--text-primary)' }}>
                  {co.statement}
                </p>
              </div>

            </div>
          ))}

          {cos.length === 0 && (
            <div className="bento-card" style={{ textAlign: 'center', padding: '4rem 2rem' }}>
              <p style={{ color: 'var(--text-secondary)', margin: 0, fontSize: '0.95rem' }}>
                No Course Outcomes are currently loaded. Please run the AI Ingestion Pipeline under Session Setup to begin.
              </p>
            </div>
          )}
        </div>
      </div>

      {/* Slide out chat sidebar panel */}
      {chatOpen && (
        <div style={{ width: '380px', flexShrink: 0, position: 'sticky', top: '100px' }} className="animate-fade-in">
          <MediatorChat phase={2} />
        </div>
      )}
    </div>
  );
};

export default Phase2COs;
