import React from 'react';
import { useSession } from '../context/SessionContext';
import { Target, CheckCircle2, ChevronRight } from 'lucide-react';

const Phase2COs = () => {
  const { sessionData } = useSession();

  if (!sessionData) return <div className="page-wrapper" style={{ color: 'var(--text-secondary)' }}>Retrieving active session metrics...</div>;

  const cos = [...(sessionData.cos || [])].sort((a, b) => 
    a.co_id.localeCompare(b.co_id, undefined, { numeric: true, sensitivity: 'base' })
  );

  return (
    <div className="page-wrapper animate-fade-in" style={{ display: 'flex', gap: '2.5rem', alignItems: 'flex-start' }}>
      
      {/* Course Outcomes Panel */}
      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', gap: '1.75rem' }}>
        
        {/* Panel Header */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div>
            <h2 style={{ fontSize: '1.6rem', marginBottom: '0.25rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              Course Outcomes (CO)
              {sessionData.is_locked && (
                <span style={{ fontSize: '0.8rem', background: '#FF453A', color: '#000', padding: '0.2rem 0.5rem', borderRadius: '4px', border: '1px solid #000' }}>
                  🔒 Locked
                </span>
              )}
            </h2>
            <p style={{ color: 'var(--text-secondary)', margin: 0, fontSize: '0.85rem' }}>
              Review the curriculum outcomes generated by the Bloom Taxonomy Agent.
            </p>
          </div>
        </div>

        {/* CO Cards Container */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
          {cos.map((co, index) => (
            <div key={co.co_id} className="bento-card" style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
              
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                  <div style={{
                    width: '32px',
                    height: '32px',
                    borderRadius: '4px',
                    background: 'var(--aurora-purple)',
                    border: '2px solid var(--border-thick)',
                    display: 'grid',
                    placeItems: 'center',
                    fontWeight: '800',
                    color: 'var(--text-dark)',
                    boxShadow: '1.5px 1.5px 0px #000000',
                    fontFamily: "'Space Grotesk', sans-serif"
                  }}>
                    {index + 1}
                  </div>
                  <h3 style={{ margin: 0, fontSize: '1.2rem' }}>{co.co_id}</h3>
                </div>
                
                <div style={{ display: 'flex', gap: '0.5rem' }}>
                  <span className="badge-bloom">{co.blooms_level}</span>
                  <span className="badge-bloom" style={{ background: 'var(--aurora-amber)', color: '#000' }}>
                    {co.blooms_keyword}
                  </span>
                </div>
              </div>

              <div style={{
                background: 'var(--surface-elevate)',
                padding: '1.25rem',
                borderRadius: '4px',
                border: '2px solid var(--border-thick)',
                color: 'var(--text-primary)',
                fontFamily: "'Plus Jakarta Sans', sans-serif",
                fontSize: '1.05rem',
                lineHeight: '1.5'
              }}>
                "{co.statement}"
              </div>

              <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--text-secondary)', fontSize: '0.8rem' }}>
                <CheckCircle2 size={14} color="var(--aurora-emerald)" />
                <span>Verified by Curriculum Validator Agent</span>
              </div>
            </div>
          ))}
          
          {cos.length === 0 && (
            <div style={{ textAlign: 'center', color: 'var(--text-secondary)', padding: '2rem' }}>
              No Course Outcomes generated yet.
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default Phase2COs;
