"""Initial schema

Revision ID: e4298643ad16
Revises: 
Create Date: 2026-05-22 10:50:58.129901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4298643ad16'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('departments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('institution_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'code')
    )
    op.create_table('subjects',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('department_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'code')
    )
    op.create_table('teachers',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('department_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('co_history',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('subject_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('co_id', sa.String(length=10), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('blooms_level', sa.Integer(), nullable=False),
    sa.Column('avg_attainment', sa.Float(), nullable=True),
    sa.Column('achieved_level', sa.Integer(), nullable=True),
    sa.Column('was_weak', sa.Boolean(), nullable=True),
    sa.Column('contributing_po_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('teacher_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('subject_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('year_of_study', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('current_phase', sa.Integer(), nullable=True),
    sa.Column('level1_threshold', sa.Float(), nullable=True),
    sa.Column('level2_threshold', sa.Float(), nullable=True),
    sa.Column('level3_threshold', sa.Float(), nullable=True),
    sa.Column('syllabus_text', sa.Text(), nullable=True),
    sa.Column('teaching_philosophy', sa.Text(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('excel_report_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('session_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('agent', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('co_po_mappings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('session_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('co_id', sa.String(length=10), nullable=False),
    sa.Column('po_id', sa.String(length=10), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=True),
    sa.Column('manually_overridden', sa.Boolean(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.CheckConstraint('strength BETWEEN 0 AND 3'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'co_id', 'po_id')
    )
    op.create_table('course_outcomes',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('session_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('co_id', sa.String(length=10), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('blooms_level', sa.Integer(), nullable=False),
    sa.Column('blooms_keyword', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('validation_status', sa.String(length=20), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mediator_chats',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('session_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('phase', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('pending_changes', sa.JSON(), nullable=True),
    sa.Column('changes_applied', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program_outcomes',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('session_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('po_id', sa.String(length=10), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('session_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('target', sa.String(length=20), nullable=False),
    sa.Column('issue', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('teacher_note', sa.Text(), nullable=True),
    sa.Column('implemented', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_batches',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('session_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('batch_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_co_ids', sa.JSON(), nullable=False),
    sa.Column('target_po_ids', sa.JSON(), nullable=True),
    sa.Column('max_marks', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['student_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('co_attainment',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('batch_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('co_id', sa.String(length=10), nullable=False),
    sa.Column('avg_percentage', sa.Float(), nullable=False),
    sa.Column('level_1_students_pct', sa.Float(), nullable=False),
    sa.Column('level_2_students_pct', sa.Float(), nullable=False),
    sa.Column('level_3_students_pct', sa.Float(), nullable=False),
    sa.Column('achieved_level', sa.Integer(), nullable=False),
    sa.Column('threshold_used', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['student_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'co_id')
    )
    op.create_table('po_attainment',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('batch_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('po_id', sa.String(length=10), nullable=False),
    sa.Column('weighted_attainment', sa.Float(), nullable=False),
    sa.Column('contributing_cos', sa.JSON(), nullable=False),
    sa.Column('is_weak', sa.Boolean(), nullable=False),
    sa.Column('weakness_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['student_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'po_id')
    )
    op.create_table('students',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('batch_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('roll_no', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['student_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'roll_no')
    )
    op.create_table('student_marks',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('student_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('assignment_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('marks_obtained', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'assignment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_marks')
    op.drop_table('students')
    op.drop_table('po_attainment')
    op.drop_table('co_attainment')
    op.drop_table('assignments')
    op.drop_table('student_batches')
    op.drop_table('recommendations')
    op.drop_table('program_outcomes')
    op.drop_table('mediator_chats')
    op.drop_table('course_outcomes')
    op.drop_table('co_po_mappings')
    op.drop_table('audit_logs')
    op.drop_table('sessions')
    op.drop_table('co_history')
    op.drop_table('teachers')
    op.drop_table('subjects')
    op.drop_table('departments')
    op.drop_table('institutions')
    # ### end Alembic commands ###
